<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\UserController::edit' => ['privates', '.service_locator.O._P6q5', 'get_ServiceLocator_O_P6q5Service.php', true],
    'App\\Controller\\UserController::login' => ['privates', '.service_locator.O._P6q5', 'get_ServiceLocator_O_P6q5Service.php', true],
    'App\\Controller\\VideoController::create' => ['privates', '.service_locator.O._P6q5', 'get_ServiceLocator_O_P6q5Service.php', true],
    'App\\Controller\\VideoController::remove' => ['privates', '.service_locator.O._P6q5', 'get_ServiceLocator_O_P6q5Service.php', true],
    'App\\Controller\\VideoController::video' => ['privates', '.service_locator.O._P6q5', 'get_ServiceLocator_O_P6q5Service.php', true],
    'App\\Controller\\VideoController::videos' => ['privates', '.service_locator.Xo8VEUb', 'get_ServiceLocator_Xo8VEUbService.php', true],
    'App\\Controller\\UserController:edit' => ['privates', '.service_locator.O._P6q5', 'get_ServiceLocator_O_P6q5Service.php', true],
    'App\\Controller\\UserController:login' => ['privates', '.service_locator.O._P6q5', 'get_ServiceLocator_O_P6q5Service.php', true],
    'App\\Controller\\VideoController:create' => ['privates', '.service_locator.O._P6q5', 'get_ServiceLocator_O_P6q5Service.php', true],
    'App\\Controller\\VideoController:remove' => ['privates', '.service_locator.O._P6q5', 'get_ServiceLocator_O_P6q5Service.php', true],
    'App\\Controller\\VideoController:video' => ['privates', '.service_locator.O._P6q5', 'get_ServiceLocator_O_P6q5Service.php', true],
    'App\\Controller\\VideoController:videos' => ['privates', '.service_locator.Xo8VEUb', 'get_ServiceLocator_Xo8VEUbService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
