<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxZxN6w\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxZxN6w/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVxZxN6w.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVxZxN6w\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVxZxN6w\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VxZxN6w',
    'container.build_id' => '830d698e',
    'container.build_time' => 1606346194,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxZxN6w');
